language: python
python:
- 3.7
- 3.8
install:
- pip install .
script:
- get_station -n CB
deploy:
  provider: pypi
  username: "__token__"
  password: pypi-AgEIcHlwaS5vcmcCJGU2OTY0ZDg1LWE5ZDItNDcxZS1hODZlLTRkZTRiMjMxNzdkMwACN3sicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJicW1haWwiXX0sICJ2ZXJzaW9uIjogMX0AAAYgK31tVw1vVRP3sDxnp-eELoFEru8Y-D2umzJZ-YYAT40
  on:
    python: 3.7
    tags: true
    branch: master